buildscript {
    ext.kotlin_version = '2.0.10'  // Correct latest Kotlin version
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.android.tools.build:gradle:8.0.1'
        classpath 'com.google.gms:google-services:4.3.10' // Check for the latest version
        classpath 'com.google.firebase:firebase-firestore:24.7.0' // Or the latest compatible version

    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = "../build"

subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
    project.evaluationDependsOn(":app")
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
